databases:
  - name: growsafe-db
    plan: free

services:
  - type: web
    name: growsafe-web
    runtime: python
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: growsafe-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: growsafe-redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0

  - type: worker
    name: growsafe-celery-worker
    runtime: python
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "celery -A config worker --loglevel=info --concurrency=2"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: growsafe-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: growsafe-redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true

  - type: worker
    name: growsafe-celery-beat
    runtime: python
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "celery -A config beat --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: growsafe-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: growsafe-redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true

  - type: redis
    name: growsafe-redis
    ipAllowList: []
    plan: starter
