# Generated by Django 5.1.5 on 2026-07-11 14:48

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("batches", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("scan_count", models.IntegerField(default=0)),
                ("first_scanned_at", models.DateTimeField(blank=True, null=True)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                ("qr_image_path", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to="batches.batch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ScanEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=50)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("genuine", "Genuine"),
                            ("already_used", "Already Used"),
                            ("recalled", "Recalled"),
                            ("invalid", "Invalid"),
                            ("expired", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("qr", "QR Code"),
                            ("sms", "SMS"),
                            ("ussd", "USSD"),
                            ("web", "Web"),
                        ],
                        default="qr",
                        max_length=10,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                (
                    "scanned_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_events",
                        to="tenants.company",
                    ),
                ),
                (
                    "verification_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_events",
                        to="verification.verificationcode",
                    ),
                ),
            ],
            options={
                "ordering": ["-scanned_at"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(fields=["code"], name="verificatio_code_d39486_idx"),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(
                fields=["batch", "is_active"], name="verificatio_batch_i_60fad2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanevent",
            index=models.Index(
                fields=["code", "scanned_at"], name="verificatio_code_f1ac13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanevent",
            index=models.Index(
                fields=["company", "scanned_at"], name="verificatio_company_1b60fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanevent",
            index=models.Index(
                fields=["result", "scanned_at"], name="verificatio_result_1494fb_idx"
            ),
        ),
    ]
