# Generated by Django 5.1.5 on 2026-07-11 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, unique=True)),
                ("quantity", models.IntegerField(default=0)),
                ("manufacture_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("manufactured", "Manufactured"),
                            ("released", "Released"),
                            ("distributed", "Distributed"),
                            ("active", "Active"),
                            ("recalled", "Recalled"),
                            ("expired", "Expired"),
                            ("destroyed", "Destroyed"),
                        ],
                        default="manufactured",
                        max_length=20,
                    ),
                ),
                ("codes_generated", models.BooleanField(default=False)),
                ("codes_generated_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
